name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner (you can also use a self-hosted runner)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Use your private key as a GitHub secret

    - name: Build Docker Image
      run: docker build -t my-html-app .

    - name: SSH to EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Stop and remove the old container if it exists
          docker stop my-html-container || true
          docker rm my-html-container || true
          # Run the new container
          docker run -d -p 80:80 --name my-html-container my-html-app
        EOF
